name       : libabigail
version    : 2.0
release    : 2
source     :
    - http://mirrors.kernel.org/sourceware/libabigail/libabigail-2.0.tar.gz : 3704ae97a56bf076ca08fb5dea6b21db998fbbf14c4f9de12824b78db53b6fda
license    : Apache-2.0 WITH LLVM-exception
component  : programming.tools
summary    : The project aims at providing a library to manipulate ABI corpora, compare them, provide detailed information about their differences and help build tools to infer interesting conclusions about
    these differences.
description: |
    This project aims at providing a C++ library for constructing, manipulating, serializing and de-serializing ABI-relevant artifacts. The set of artifacts that we are interested in is made of constructions like types, variables, functions and declarations of a given library or program. For a given program or library, this set of constructions is called an ABI corpus.
builddeps  :
    - pkgconfig(libelf)
    - pkgconfig(libdw)
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
